// Generated by CoffeeScript 1.7.1
var Graphics,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

Graphics = (function() {
  function Graphics(w, h) {
    this.w = w;
    this.h = h;
    this.update = __bind(this.update, this);
    this.showText = __bind(this.showText, this);
    this.svg = d3.select('svg');
    this.svg.attr('width', this.w).attr('height', this.h);
  }

  Graphics.prototype.showText = function(text) {
    return this.svg.append('text').attr('x', this.w / 2).attr('y', this.h / 2).data('Game over');
  };

  Graphics.prototype.update = function(elements) {
    var g, newG;
    g = this.svg.selectAll('g').data(elements, function(e) {
      return e.id;
    });
    newG = g.enter().append('g').each(function(element, i) {
      return element.drawFunction()(d3.select(this));
    });
    g.attr('transform', function(e) {
      return "translate(" + (e.pos.x - e.sizeX()) + "," + (e.pos.y - e.sizeY()) + ")";
    });
    return g.exit().remove();
  };

  Graphics.drawRocket = function(g) {
    console.log('rocket');
    return g.append('circle').attr('r', function(e) {
      return e.r;
    }).attr('cx', function(e) {
      return e.r;
    }).attr('cy', function(e) {
      return e.r;
    }).attr('fill', function(e) {
      return e.color;
    });
  };

  Graphics.drawPlanet = function(g) {
    g.append('circle').attr('r', function(e) {
      return e.field;
    }).attr('cx', function(e) {
      return e.field;
    }).attr('cy', function(e) {
      return e.field;
    }).attr('fill', function(e) {
      return d3.rgb(240, 240, 240);
    });
    return g.append('circle').attr('r', function(e) {
      return e.r;
    }).attr('cx', function(e) {
      return e.field;
    }).attr('cy', function(e) {
      return e.field;
    }).attr('fill', function(e) {
      return e.color;
    });
  };

  Graphics.drawObstacle = function(g) {
    return g.append('circle').attr('r', function(e) {
      return e.r;
    }).attr('cx', function(e) {
      return e.r;
    }).attr('cy', function(e) {
      return e.r;
    }).attr('fill', function(e) {
      return e.color;
    });
  };

  return Graphics;

})();
